# Generated by Django 3.1.8 on 2023-01-23 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210418_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Registered User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='AAdhar number. Must be unique', max_length=20, null=True, verbose_name='aadhar number'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, help_text="International format of borrower's contact number. Phone number if provided must be unique", max_length=20, null=True, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='user',
            name='country_of_residence',
            field=models.CharField(blank=True, help_text='The country of residence of borrower', max_length=125, null=True, verbose_name='country of residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_address',
            field=models.CharField(blank=True, help_text='The current living address of the borrower. Verification is required', max_length=1000, null=True, verbose_name='current address'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of borrower. Registered borrowers must be not less than 18 years of age ', null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='default_currency',
            field=models.CharField(blank=True, default='INR', help_text='The default currency of borrower', max_length=3, null=True, verbose_name='default currency'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='The job title of borrower', max_length=125, null=True, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete',
            field=models.BooleanField(default=False, help_text='Indication if borrower has completing KYC verification processes', verbose_name='kyc_complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_complete_date',
            field=models.DateTimeField(blank=True, help_text='KYC complete date', null=True, verbose_name='date of kyc completion'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('pending', 'Pending'), ('action_required', 'Action Required'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='unverified', help_text='kyc status of the client.', max_length=20, verbose_name='kyc status'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_submitted',
            field=models.BooleanField(default=False, help_text='Indication if borrower has submitted KYC verification processes', verbose_name='kyc submitted'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete',
            field=models.BooleanField(default=False, help_text='on boarding status of the client.', verbose_name='on boarding status'),
        ),
        migrations.AddField(
            model_name='user',
            name='on_boarding_complete_date',
            field=models.DateTimeField(blank=True, help_text='on boarding complete date', null=True, verbose_name='date of on_boarding completion'),
        ),
        migrations.AddField(
            model_name='user',
            name='permanent_address',
            field=models.CharField(blank=True, help_text='Permanent living address of the borrower. Verification and privacy rules applies', max_length=1000, null=True, verbose_name='permanent address'),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, help_text='The birth place of borrower', max_length=125, null=True, verbose_name='place of birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_ip_address',
            field=models.CharField(blank=True, help_text='The registered ip address of client', max_length=125, null=True, verbose_name='registered ip address'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='The verification date of borrower', null=True, verbose_name='verification date'),
        ),
    ]
