# Generated by Django 3.1.8 on 2023-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230123_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Email address of the client.', max_length=125, unique=True, verbose_name='Email Address'),
        ),
    ]
